homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  external_url: !secret external_url
  internal_url: !secret internal_url

  packages: !include_dir_merge_named configuration/package

config:
frontend:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
updater:
zone:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5

recorder: !include configuration/recorder.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named configuration/group
automation: !include_dir_merge_named configuration/automation
script: !include_dir_merge_named configuration/script
scene: !include_dir_merge_named configuration/scene
sensor: !include_dir_merge_named configuration/sensor
