
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  external_url: !secret external_url
  internal_url: !secret internal_url

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5

recorder: !include configuration/recorder.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named configuration/group
automation: !include_dir_merge_named configuration/automation
script: !include_dir_merge_named configuration/script
scene: !include_dir_merge_named configuration/scene
