# This loads the default set of tools and integrations used by hassio

default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_merge_named configuration/package/

frontend: 
  themes: !include_dir_merge_named configuration/theme/

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5

recorder: !include configuration/integrations/recorder.yaml

tts:
  - platform: google_translate

# Used to enable live stream from camera
# https://www.home-assistant.io/integrations/stream
stream:

camera: !include configuration/integrations/camera.yaml

tplink: !include configuration/integrations/tplink.yaml

spotify: !include configuration/integrations/spotify.yaml

notify: !include_dir_merge_list configuration/notify/
automation: !include_dir_merge_list configuration/automation/

group: !include_dir_merge_named configuration/group/
script: !include_dir_merge_named configuration/script/
scene: !include_dir_merge_named configuration/scene/
sensor: !include_dir_merge_named configuration/sensor/
