---
# 
# Importing all automations
#
# https://www.home-assistant.io/docs/automation/

automation: !include_dir_merge_list ../automations/
automation manual: !include_dir_merge_list ../automations.yaml