---
# 
# Sensors relating to the International Space Station
#
# Based upon answer from https://community.home-assistant.io/t/international-space-station-sensor/9760/26

- platform: rest
  name: ISS Coordinates
  json_attributes:
    - timestamp
    - iss_position
    - latitude
    - longitude
  resource: 'http://api.open-notify.org/iss-now.json'
  scan_interval:
    seconds: 15

- platform: rest
  name: ISS Pass times
  json_attributes:
    - request
    - response
  value_template: >
    {{ value_json.message }}
  resource: !secret iss_pass_times_url
  scan_interval:
    seconds: 300

- platform: rest
  name: ISS People in space
  json_attributes:
    - people
    - number
  value_template: "{{ value_json['number'] }}"
  resource: 'http://api.open-notify.org/astros.json'
