---
# 
# This package contains the automation for sending motion notifications
#

- alias: WDC01CAM01 Motion Detected
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01
      value_template: "{{ value_json.url }}"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: Motion Detected!
        data:
          url: "{{ trigger.payload.url }}"
          group: Hassio
          priority: high
