---
# 
# This package contains the automation for sending motion notifications
#

- alias: WDC01CAM01 Motion Recorded
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01/record
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: WDC01CAM01
        message: Motion Recorded {{ "\u25b6\ufe0f" }}
        data:
          clickAction: "{{ trigger.payload_json.url }}"
          image: "{{ trigger.payload_json.image }}"
          tag: "{{ trigger.payload_json.tag }}"
          group: Hassio
          priority: high

- alias: WDC01CAM01 Motion Detected
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01/detect
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: WDC01CAM01
        message: Motion Detected {{ "\ud83d\udd34" }}
        data:
          tag: "{{ trigger.payload_json.tag }}"
          clickAction: "{{ trigger.payload_json.url }}"
          image: "{{ trigger.payload_json.image }}"
          group: Hassio
          priority: high
