---
# 
# This package contains the automation for sending motion notifications
#

- alias: WDC01CAM01 Motion Recorded
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01/record
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: WDC01CAM01 Motion Recorded
        data:
          clickAction: "{{ trigger.payload_json.url }}"
          image: "{{ trigger.payload_json.image }}"
          tag: "{{ trigger.payload_json.url }}"
          group: Hassio
          priority: high

- alias: WDC01CAM01 Motion Detected
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01/detect
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: WDC01CAM01 Motion Detected
        data:
          tag: "{{ trigger.payload_json.detail }}"
          clickAction: "{{ trigger.payload_json.url }}"
          group: Hassio
          priority: high
