---
# 
# This package contains the automation for sending motion notifications
#

- alias: WDC01CAM01 Motion Detected
  trigger:
    - platform: mqtt
      topic: motion/WDC01CAM01
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: Motion Detected!
        data:
          clickAction: "{{ trigger.payload.url }}"
          image: "{{ trigger.payload.image }}"
          group: Hassio
          priority: high
